"""init_tables

Revision ID: f4541dda76ab
Revises:
Create Date: 2026-05-17 17:55:36.106644

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4541dda76ab"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "properties",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_name", sa.String(), nullable=False),
        sa.Column("source_url", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("price_text", sa.String(), nullable=True),
        sa.Column("price_int", sa.Integer(), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("is_geocoded", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # 💡 重複エラーを防ぐため、idx_properties_geom の明示的な作成をコメントアウト
    # op.create_index('idx_properties_geom', 'properties', ['geom'], unique=False, postgresql_using='gist')

    op.create_index(
        op.f("ix_properties_address"), "properties", ["address"], unique=False
    )
    op.create_index(op.f("ix_properties_id"), "properties", ["id"], unique=False)
    op.create_index(op.f("ix_properties_name"), "properties", ["name"], unique=False)
    op.create_index(
        op.f("ix_properties_price_int"), "properties", ["price_int"], unique=False
    )
    op.create_index(
        op.f("ix_properties_site_name"), "properties", ["site_name"], unique=False
    )
    op.create_index(
        op.f("ix_properties_source_url"), "properties", ["source_url"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_properties_source_url"), table_name="properties")
    op.drop_index(op.f("ix_properties_site_name"), table_name="properties")
    op.drop_index(op.f("ix_properties_price_int"), table_name="properties")
    op.drop_index(op.f("ix_properties_name"), table_name="properties")
    op.drop_index(op.f("ix_properties_id"), table_name="properties")
    op.drop_index(op.f("ix_properties_address"), table_name="properties")

    # 💡 upgrade側で明示的に作っていないため、削除命令もコメントアウト
    # op.drop_index('idx_properties_geom', table_name='properties', postgresql_using='gist')

    op.drop_table("properties")
    # ### end Alembic commands ###
